services:
  traefik:
    image: traefik:3.2.1
    container_name: traefik
    command:
      - "--api.insecure=true"                  # Enable Traefik dashboard (optional for development)
      - "--providers.docker=true"             # Enable Docker provider
      - "--providers.docker.exposedbydefault=false" # Require explicit exposure of services
      - "--entrypoints.web.address=:80"       # Define web entry point
    ports:
      - "80:80"                               # External HTTP traffic
      - "8080:8080"                           # Traefik dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Access Docker API for service discovery
    restart: unless-stopped

  arangodb:
    image: arangodb:latest
    container_name: attack-shuffle-arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    volumes:
      - arangodb-data:/var/lib/arangodb3
      - ./arangodb/init:/docker-entrypoint-initdb.d
    labels:
      - "traefik.enable=true"                             # Enable Traefik for this service
      - "traefik.http.routers.arangodb.rule=Host(`arangodb.localhost`)" # Routing rule
      - "traefik.http.routers.arangodb.entrypoints=web"   # Use web entry point
      - "traefik.http.services.arangodb.loadbalancer.server.port=8529" # ArangoDB internal port

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    depends_on:
      - arangodb
    environment:
      - VUE_APP_API_URL=http://arangodb.localhost         # API URL for Vue frontend
    labels:
      - "traefik.enable=true"                             # Enable Traefik for this service
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)" # Routing rule
      - "traefik.http.routers.frontend.entrypoints=web"   # Use web entry point
      - "traefik.http.services.frontend.loadbalancer.server.port=8080" # Frontend internal port

volumes:
  arangodb-data:
