# traefik-dynamic.yml

http:
  middlewares:
    # CrowdSec Bouncer Middleware
    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          apiUrl: "http://crowdsec:8080"          # Replace with the CrowdSec service URL
          apiKey: "${CROWDSEC_BOUNCER_API_KEY}"   # CrowdSec API key from environment variables

    # Authentik ForwardAuth Middleware
    authentik:
      forwardAuth:
        address: "http://authentik:9000/outpost.goauthentik.io/auth/traefik"  # Authentik outpost URL
        trustForwardHeader: true
        authResponseHeaders:
          - "X-authentik-username"
          - "X-authentik-groups"
          - "X-authentik-email"

  routers:
    # Define the router for the application with both middlewares applied
    app-router:
      entryPoints:
        - websecure
      rule: "Host(`${TRAEFIK_DOMAIN}`)"
      service: app-service
      tls:
        certResolver: cloudflare
      middlewares:
        - crowdsec-bouncer
        - authentik

  services:
    # Define the application service
    app-service:
      loadBalancer:
        servers:
          - url: "http://app:${APP_PORT}"  # Reference to the app service's internal Docker URL
