http:
  routers:
    # Router for Vue frontend
    frontend-router:
      rule: "Host(`frontend.localhost`)"       # Route based on host
      entryPoints:
        - web
      service: frontend-service
      middlewares:
        - secure-headers

    # Router for ArangoDB backend
    arangodb-router:
      rule: "Host(`arangodb.localhost`)"       # Route based on host
      entryPoints:
        - web
      service: arangodb-service
      middlewares:
        - secure-headers

    # Router for Traefik dashboard (optional for development)
    traefik-dashboard-router:
      rule: "Host(`dashboard.localhost`)"      # Route based on host
      entryPoints:
        - web
      service: api@internal
      middlewares:
        - secure-headers

  services:
    # Service for Vue frontend
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://vue-frontend:8080"    # Internal URL of the frontend container

    # Service for ArangoDB backend
    arangodb-service:
      loadBalancer:
        servers:
          - url: "http://attack-shuffle-arangodb:8529" # Internal URL of the ArangoDB container

  middlewares:
    # Middleware for security headers
    secure-headers:
      headers:
        frameDeny: true                       # Prevent clickjacking
        contentTypeNosniff: true              # Prevent MIME type sniffing
        browserXssFilter: true                # Enable XSS protection in browsers
        stsSeconds: 31536000                  # Enable HTTP Strict Transport Security (HSTS)
        stsIncludeSubdomains: true            # Apply HSTS to subdomains
        stsPreload: true                      # Allow domain to be preloaded in HSTS lists
